### ISSUE TITLE
TrackMe bug report -  DHM thresholds overwritten with default values 

### ISSUE THREAD

**Issue by kruj0** [trackme-limited/trackme-report-issues#599]
**Describe the bug**
This week i updated 2 customers to the newest version and both have DHM in place.
Since the newest version is running, the thresholds are lost, which were typed manually in.   

the last version where im sure this issue was not there, was the 2.0.45.

**TrackMe version**
Version:
2.0.90 & 2.0.88

**To Reproduce**
Setup DSM and DHM monitoring and upgrade to the newest version.
Change the threshold from the default to something else inside of DHM.
Wait 5-10 minutes. And have a look into the DHM again.  

**Expected behavior**
No overwritten values.

**Screenshots**
wouldn't help here.

**Splunk version and deployment:**
Based on 2 customers:
One is on 9.0.5.1 (SHC splunk enterprise onprem)
The other one is on 9.0.8 (standalone search head)

**Additional context**
After small troubleshooting deep dives i guess there is a change inside of one eval which is chained between the hybrid trackers and the tracking types (DSM & DHM). 
Looks like the trackers overwrites the value with the default, may because the typed value from the browser is a string and one of the evals will check 

> (if(isnum('typed_value' ..., use it,default)...
 
if you need more infos, please let me know. we will not roll back for now.

**Comment by guilhemmarchand** [comment]
Hi @kruj0 

There was a regression in 2.0.88/.20.89 when the adaptive thresholding tracker was running and updating entites could lead to the loss of some fields like the latency threshold.
Now, there might be some confiusion with new features, notably because the jump in version was very large:

https://docs.trackme-solutions.com/latest/user_guide_splk_feeds_thresholds.html#adaptive-delay-tresholds-with-machine-learning-since-trackme-v2-0-72

I believe eventually we should meet and discuss this? Can you drop us an email at support@trackme-solutions.com when convenient

**Comment by beutebayer** [comment]
We have the same issue in our environment (TrackMe 2.0.85 on Standalone Splunk 9.1.3).

I tried to configure the "Maximal allowed delay value" for several entities.. after some minutes it gets reconfigured to the default of 3600.

**Comment by guilhemmarchand** [comment]
@beutebayer 
To confirm, this issue was fixed and cannot happen in TrackMe 2.0.90 (which is now vetted if you are on Splunk Cloud)
Please upgrade to this release and revert in case of any persistent issue

Sorry for inconvenience

**Comment by kruj0** [comment]
@guilhemmarchand  thanks for the docu link. with this i understood the mechanic in the background and now i can setup it like we have it before the update. (disable it)


from my point of view, we can close this bug. 
But it would be really friendly to don't force new defaults in a release where for example thresholds will be overwritten with a new feature.
It would be better if a new feature is disabled per default and need to be enabled inside a app update.
otherwise the trackme user / customer will lost the thresholds which were setup because of reasons/usecases.

May you can also change something inside the gui. For example if the adative delay is set to true, the other inputs inside the gui will be disabled / gray out and a hint will be displayed.

**Comment by kruj0** [comment]
@guilhemmarchand  need sadly to reopen this ticket.
i disabled the *Adaptive delay globally and made some tests inside DHM.
one entry works as it should. it takes my manual delay value and it will not be overwritten.

on another entry (2nd from the table) it will be overwritten with the default values again.
From the audit changes view i can see that there is a update monitoring lag policy running:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/39763401/0a771e5e-f9f4-46ab-835a-af45a13e2246)

```
 _time: 1715176944.298172
   action: success
   change_type: update monitoring lag policy
   comment: N/A
   object: key:host|xyz.host2nd.dot
...
 "data_max_lag_allowed": 3602,
 "data_max_delay_allowed": 3602,
 "summary_max_lag_allowed": "3600",
 "summary_max_delay_allowed": "3600",
...
 "allow_adaptive_delay": "false"
}
```

i also disabled the saved search trackme_dhm_adaptive_delay_tracker_tenant_xyz, in the hope that this tracker may reset something. but it must be another one.

**Comment by beutebayer** [comment]
@guilhemmarchand 
Upgrade didn't help.

I upgraded to 2.0.90, disabled "Adaptive delay" and "Enable Machine Learning" but the value "Maximal allowed delay value" in DHM still get reconfigured to default of 3600, in DSM the values remain as configured.

**Comment by guilhemmarchand** [comment]
Can you test the following please @beutebayer:

- Create a brand new testing tenant, enable splk-dhm only, target a few of your hosts (set a root constraint to a few indexes, etc)
- Once you have some hosts, please test the same in this temporary testing tenant

If you have already the max number of virtual tenants or trackers in the free version, please temporarily enable the developer mode

This would be the easiest to make sure it's not due to some resilient existing configuration

**Comment by beutebayer** [comment]
@guilhemmarchand 
Created a new tenant with dhm only and disabled "Adaptive delay" and "Enable Machine Learning" but still having the issue.

**Comment by guilhemmarchand** [comment]
Hi @beutebayer @kruj0 

The issue was reproduced and identfiied properly, this indeed is a regression and non expected behaviour linked to the major Python changes that were performed in TrackMe to allow pagination and other very important optimizations.

This is fixed in TrackMe 2.0.91 which is entering the last round of qualification and is planned to tbe published today, I will confirm here when the new release is published effectively.

My aplogises for any convenience on this one

**Comment by guilhemmarchand** [comment]
@kruj0 
@beutebayer 

TrackMe 2.0.91 is now live in Splunk Base, I will keep this issue opened until we all agree that the issue is now fixed ;-) (which I am confident it is)

Thank you for your patience.

**Comment by kruj0** [comment]
@guilhemmarchand ,
thanks! can confirm its fixed now. 

@beutebayer  if its okay for you, i would close this issue.

**Comment by beutebayer** [comment]
@kruj0 sure, I‘m fine with closing.

**Comment by guilhemmarchand** [comment]
Many thanks @kruj0 @beutebayer !

**Comment by guilhemmarchand** [comment]
@kruj0 
@beutebayer 

We have detected a strong regression in 2.0.91 regarding an update made to reduce risks of generating skipping search, in short due to Appinspect contraints we cannot have a hidden directory and our automatically remove these (if any), this Python module (numpy) required this to work and we didn't notice the regression before the app was submitted. (and unfortunately vetted in just a few hours... what a bad luck!)

Nevertheless, please ensure you run 2.0.92 and not 2.0.91, the 2.0.91 release was also made no visible in Splunk Base.
